remove deprecated pickImage method
googlecodelabs/photos-sharing pull request #26
Opened 2020-06-29 08:54 UTC by guyo13

2020-07-09 03:25 UTC, jfschmakeit requested changes
Thanks for submitting this pull request!

We also need to bump the version of the `image_picker` dependency in the `pubspec.yaml` file.

2020-07-09 03:25 UTC, jfschmakeit commented on lib/components/contribute_photo_dialog.dart
> +  ImagePicker imagePicker = ImagePicker();
```suggestion
  final _imagePicker = ImagePicker();
```
Per the README for the image_picker package, it looks like this should be final.

2020-07-09 03:25 UTC, jfschmakeit commented on lib/components/contribute_photo_dialog.dart
> +    final File image = await imagePicker.getImage(
```suggestion
    final File image = await _imagePicker.getImage(
```

2020-07-12 08:33 UTC, guyo13 commented
@jfschmakeit I added the changes you requested

2020-07-14 04:10 UTC, jfschmakeit commented
Please also update the `image_picker` dependency to version `^0.6.7+4` in the `pubspec.yaml` file.  (The new methods were only added in `0.6.7` so we need to update the dependency too.)

2020-07-16 05:50 UTC, guyo13 commented
Done !

2020-07-29 01:14 UTC, merged

2020-07-29 01:14 UTC, jfschmakeit commented
Apologies for the delay - but thanks for preparing this change. I will go ahead and update the steps in the codelab as well.